### ISSUE TITLE
Unable to fire handle_errors* methods

### ISSUE THREAD

**Issue by systemnate** [minimul/qbo_rails#4]
Hi, minimul.  In my app I am working on, I have implemented some behavior very similar to your examples dealing with customers.  When I create a new customer, it adds the qbo_id and everything is fine.  However, when I try to update an existing customer, I get the `Duplicate Name Exists Error`.  Per your README, I have created a file in `app/services/qbo_rails/error_handler.rb` with the same contents you have in your README (plus a fix for a missing end).  I even added these folders to my autoload_path.  For the life of me, I cannot seem to get this method to fire.  I took a look at the source and it looks like it should work, but it is like Rails is not picking up my file (despite adding to autoload and restarting server).  Any ideas on what I could be doing wrong?

**Comment by minimul** [comment]
1.
You are not populating the `customer.qbo_id`. Check that `customer.qbo_id` has a value before doing a `.create_or_update`.
1. Post the contents of your `app/services/qbo_rails/error_handler.rb` file.

**Comment by systemnate** [comment]
When I create a new user (or "contact" in my app) (with no name conflicts in QBO), it successfully creates the customer in QBO and populated my contact.qbo_id.  If I try to edit/create a new customer whose name already exists in QBO, I get the `"Duplicate Name Exists Error"` in my server log (and of course qbo_id does not get populated in this case).  In my `contacts_controller`, I have the following logic for create and updates:

```
...
    respond_to do |format|
      if @contact.save
        qbo_rails = QboRails.new(QboConfig.last, :customer)
        qb_customer = qbo_rails.base.qr_model(:customer)
        qb_customer.display_name = @contact.name

        phone = qbo_rails.base.qr_model(:telephone_number)
        phone.free_form_number = @contact.phone_number

        address = qbo_rails.base.qr_model(:physical_address)
        address.line1 = @contact.address
        address.city =  @contact.city
        address.country_sub_division_code = @contact.state
        address.postal_code = @contact.postal_code

        qb_customer.billing_address = address
        qb_customer.primary_phone = phone
       qbo_rails.create_or_update(@contact, qb_customer)
...
```

From what I understand in your README after creating/updating a customer that already exists, I get the `"Duplicate Name Exists Error"` and it says "...But qbo_rails can handle this by simple adding the below method with the prefix handle_error. For example in your Rails app you could add a file in app/services/qbo_rails/error_handler.rb that responds to QBO API's Duplicate Name Exists Error."

Here is what I have in `app/services/qbo_rails/error_handler.rb`.  I have also tried adding some logging to the top of the call just so I could see if it is even being called (it is not).  It's almost as though Rails does not see this code.  I'll admit that I am pretty new to the idea of putting POROs in directories other than what Rails gives by default, but I did play around with this concept by creating some random classes in the app/services directory, adding app/services to the autoload_path, and then was able to access them from inside `rails c`.  After that, I tried adding a class method to QboRails (inside app/services to just print something like "hello, world" to the screen (e.g. `def self.say_hello puts "hello, world" end`) and was unable to get this class level method to run either.  I am not sure if you do anything special in any file to get Rails to see this file?

```
class QboRails
  module ErrorHandler
    def handle_error_name_entity_already_exists(exception)
      if exception.message =~ /Duplicate Name Exists Error.*Another (customer|vendor|employee)/m
        display_name = Nokogiri::XML(exception.request_xml).at('DisplayName').content
        result = @base.find_by_display_name(display_name)
        if result.entries.size == 1
          @record.update_column(foreign_key, result.entries.first.id)
          @only_run_once = true
          @record.reload
          create_or_update(@record, @qb_record)
          true
        else
          false
        end
      else
        false
      end
    end
  end
end
```

Thanks for the reply and amazing work on your screencasts and gems.  They have been a huge help!

**Comment by minimul** [comment]
I'll have to take a closer look at your comment tomorrow. Not that there is anything bugging with this gem or quickbooks-ruby (I use them both in a Intuit App store production app) but how far are you into your integration? The reason I ask is that my latest gem `qbo_api` is way easier to use. I don't do any new projects with quickbooks-ruby, just `qbo_api`. That said, I will try to assist with using this gem.

**Comment by systemnate** [comment]
`qbo_api` looks very slick.  However, I am relatively far into the integration (I developed all the functionality as sort of an MVP with no error handling or anything and am now trying to go back and make it right)...but will most definitely consider `qbo_api` in the future.

**Comment by minimul** [comment]
Rails should autoload this file automatically. What version of Rails?

**Comment by minimul** [comment]
If you continue to bang your head just roll the `qbo_rails` code into your app natively. It is only 93 sloc's and is all found in here https://github.com/minimul/qbo_rails/blob/master/lib/qbo_rails.rb

**Comment by systemnate** [comment]
Rails 5, but will do with the qbo_rails as it does look pretty straightforward.  Thanks!
